### ISSUE TITLE
Non-maxima suppression algorithms

### ISSUE THREAD

**Issue by Nuzhny007** [mrgloom/Linear-SVM-and-HOG#1]
About Non-maxima suppression algorithms. OpenCV uses groupRectangles function or MeanShift grouping. This algorithms are more powerful that Nuzhny007/Non-Maximum-Suppression. And they used in NVidia DetectNet.

**Comment by mrgloom** [comment]
I will take a look:
groupRectangles
https://github.com/opencv/opencv/blob/fbf2383d5dfffeb7c60748be310f86327fb4a335/modules/objdetect/src/cascadedetect.cpp#L60
groupRectangles_meanshift
https://github.com/opencv/opencv/blob/fbf2383d5dfffeb7c60748be310f86327fb4a335/modules/objdetect/src/cascadedetect.cpp#L319
